---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.10.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 enthält mehrere neue Funktionen und Verbesserungen.

Zusätzliche Funktionen und Erweiterungen sind ebenfalls in den neuesten Versionen von BlueXP verfügbar. Siehe https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Entsprechende Details.



== c4-, m4- und r4-Instanzen werden nicht mehr unterstützt (28. Oktober 2022)

In AWS werden die Instanztypen c4, m4 und r4 EC2 nicht mehr mit Cloud Volumes ONTAP unterstützt. Wenn Sie ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 zu einem Instanztyp wechseln.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.



== 9.10.0 GA (4. Oktober 2021)

Die Version 9.10.0 GA ist in AWS, Azure und Google Cloud verfügbar. Diese Version umfasst die folgenden neuen Funktionen und Verbesserungen.



=== Verbesserte Schreib-Performance

Wir haben die Schreib-Performance von Cloud Volumes ONTAP verbessert, wenn die hohe Schreibgeschwindigkeit aktiviert ist.



=== Erhöhte Größe der NVRAM-Festplatte in Azure

Die Größe der NVRAM-Festplatte wurde für die neuen Cloud Volumes ONTAP Systeme in Azure von 128 gib auf 512 gib erhöht.


NOTE: Wenn Sie ein System mit einem einzelnen Node auswählen und die virtuelle Maschine Ultra SSDs unterstützt, verwendet das System für NVRAM eine Ultra SSD mit 32 gib anstatt eine Premium-SSD mit 512 gib.



== Erforderliche Version des BlueXP Connectors

Der BlueXP-Connector muss Version 3.9.11 oder höher ausführen, um neue Cloud Volumes ONTAP 9.10.0-Systeme bereitzustellen und bestehende Systeme auf 9.10.0 zu aktualisieren.



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von BlueXP abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.9.1 auf Cloud Volumes ONTAP 9.10.0 durchführen. BlueXP fordert Sie auf, Ihre vorhandenen Cloud Volumes ONTAP 9.9.1-Systeme auf Version 9.10.0 zu aktualisieren.
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie aktualisiert werden können, wenn Sie von BlueXP benachrichtigt werden"^].

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.




=== DS3_v2

Ab der Version 9.9.1 wird der DS3_v2 VM-Typ nicht mehr mit neuen und vorhandenen Cloud Volumes ONTAP-Systemen unterstützt. Wenn auf diesem VM-Typ bereits ein System ausgeführt wird, müssen Sie die VM-Typen ändern, bevor Sie auf 9.10.0 aktualisieren.
